"""baseline

Revision ID: 7163a89db02c
Revises: 
Create Date: 2026-08-31 07:12:17.995661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7163a89db02c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('sire', sa.String(), nullable=True),
    sa.Column('dam', sa.String(), nullable=True),
    sa.Column('dam_sire', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horses_dam_sire'), ['dam_sire'], unique=False)
        batch_op.create_index(batch_op.f('ix_horses_sire'), ['sire'], unique=False)

    op.create_table('jockeys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('course_type', sa.String(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('weather', sa.String(), nullable=True),
    sa.Column('track_condition', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_races_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_races_venue'), ['venue'], unique=False)

    op.create_table('trainers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('horse_id', sa.String(), nullable=False),
    sa.Column('jockey_id', sa.String(), nullable=True),
    sa.Column('trainer_id', sa.String(), nullable=True),
    sa.Column('post_position', sa.Integer(), nullable=True),
    sa.Column('horse_number', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['jockey_id'], ['jockeys.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'horse_id', name='uq_entry_race_horse')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entries_horse_id'), ['horse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_jockey_id'), ['jockey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_trainer_id'), ['trainer_id'], unique=False)

    op.create_table('payouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('bet_type', sa.String(), nullable=False),
    sa.Column('combination', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'bet_type', 'combination', name='uq_payout_race_bet_combination')
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payouts_race_id'), ['race_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('horse_id', sa.String(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_created_at'), ['created_at'], unique=False)

    op.create_table('results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('horse_id', sa.String(), nullable=False),
    sa.Column('horse_number', sa.Integer(), nullable=True),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('margin', sa.String(), nullable=True),
    sa.Column('last_3f', sa.Float(), nullable=True),
    sa.Column('jockey_name', sa.String(), nullable=True),
    sa.Column('trainer_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'horse_id', name='uq_result_race_horse')
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_results_horse_id'), ['horse_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_jockey_name'), ['jockey_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_trainer_name'), ['trainer_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_trainer_name'))
        batch_op.drop_index(batch_op.f('ix_results_race_id'))
        batch_op.drop_index(batch_op.f('ix_results_jockey_name'))
        batch_op.drop_index(batch_op.f('ix_results_horse_id'))

    op.drop_table('results')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_created_at'))

    op.drop_table('predictions')
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payouts_race_id'))

    op.drop_table('payouts')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_trainer_id'))
        batch_op.drop_index(batch_op.f('ix_entries_race_id'))
        batch_op.drop_index(batch_op.f('ix_entries_jockey_id'))
        batch_op.drop_index(batch_op.f('ix_entries_horse_id'))

    op.drop_table('entries')
    op.drop_table('trainers')
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_races_venue'))
        batch_op.drop_index(batch_op.f('ix_races_grade'))
        batch_op.drop_index(batch_op.f('ix_races_date'))

    op.drop_table('races')
    op.drop_table('jockeys')
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horses_sire'))
        batch_op.drop_index(batch_op.f('ix_horses_dam_sire'))

    op.drop_table('horses')
    # ### end Alembic commands ###
